all:	

clean:	
	rm -fr *.hi *.o ; \
	make -C Scheme clean ; \
	make -C Lvm clean ; \
	make -C Lvm/Asm clean ; \
	make -C Lvm/Core clean ; \
	make -C Lvm/Common clean ; \
	make -C Lvm/Common/ghc clean ; \
	make -C Lvm/Lvm clean
